<?php
/**
 * This file provides defaults for backends people use to change their
 * passwords.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in backends.local.php or backends.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use backends-servername.php.
 *
 * There are a number of properties that you can set for each backend:
 *
 * name: This is the plaintext, english name that you want displayed to people
 *       if you are using the drop down server list.  Also displayed on the
 *       main page (input form).
 *
 * driver: The Passwd driver used to change the password. Valid values are
 *         currently:
 *
 *              ldap:       Change the password on a ldap server
 *
 * no_reset: Do not reset the authenticated user's credentials on success.
 *
 */

// NOTE: to set the ldap userdn, see horde/config/hooks.php
$backends['ldap'] = array(
    'disabled' => false,
    'name' => 'MathLDAP Server',
    'preferred' => '',
    'driver' => 'Ldap',
    'params' => array(
        'host' => 'ldap2.math.ias.edu',
        'port' => 389,
        // Whether to enable TLS for this LDAP connection
        // Note: make sure that the host matches cn in the server certificate.
        'tls' => true,
        'basedn' => 'ou=People,dc=math,dc=ias,dc=edu',
        // LDAP object key attribute.
        'uid' => 'uid',
	// Do we support subject setting
	'subject' => true,
	// Can we change from address
	'from' => false,
        // The attribute storing the vacation message
        'vacation' => 'vacationInfo',
	// attribute determining whether it is active
	'active' => 'vacationActive',
	// value for enabled
	'enabled' => 'TRUE',
	// value for disabled
	'disabled' => 'FALSE',
	// vacation start
	'start' => 'vacationstart',
	// vacation end
	'end' => 'vacationend',
	// how often
	'howoften' => 'vacationOften'
    ),
);
